repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        args: [--line-length=100]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.6'
    hooks:
    -   id: ruff
        args: [--fix, --line-length=100]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
    -   id: mypy
        additional_dependencies:
            - types-requests
            - types-pyyaml
            - pandas-stubs
            - types-python-dateutil
        args: [--ignore-missing-imports]

-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.6
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate

-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.5
    hooks:
    -   id: sqlfluff-lint
        files: ^src/orchestrators/dbt/models/.*\.sql$
        additional_dependencies:
            - dbt-core
            - dbt-postgres 