default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 3

    prod:
      type: postgres
      host: "{{ env_var('DB_HOST', 'postgres') }}"
      user: "{{ env_var('DB_USER', 'airflow') }}"
      password: "{{ env_var('DB_PASSWORD', 'airflow') }}"
      port: "{{ env_var('DB_PORT', '5432') | as_number }}"
      dbname: "{{ env_var('DB_NAME', 'airflow') }}"
      schema: public
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
      retries: 3

    duckdb:
      type: duckdb
      path: /data/analytics.duckdb
      schema: main
      threads: 4 