name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 mypy ruff
          pip install -e ".[dev]"

      - name: Lint with flake8
        run: |
          flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src/orchestrators/airflow/dags/ --count --max-complexity=10 --max-line-length=100 --statistics

      - name: Lint with black
        run: |
          black --check --line-length 100 src/

      - name: Lint with ruff
        run: |
          ruff check src/

      - name: Type check with mypy
        run: |
          mypy src/

  test-airflow-dags:
    name: Test Airflow DAGs
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/infrastructure/docker/requirements-airflow.txt
          pip install pytest pytest-cov

      - name: Run DAG integrity tests
        run: |
          pytest src/orchestrators/airflow/tests/ -v

  test-dbt:
    name: Test dbt models
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres

      - name: Configure dbt profiles
        run: |
          mkdir -p ~/.dbt
          cat << EOF > ~/.dbt/profiles.yml
          default:
            target: ci
            outputs:
              ci:
                type: postgres
                host: localhost
                user: postgres
                password: postgres
                port: 5432
                dbname: postgres
                schema: public
                threads: 1
          EOF

      - name: Run dbt tests
        run: |
          cd src/orchestrators/dbt
          dbt deps
          dbt compile --profiles-dir ~/.dbt
          dbt test --profiles-dir ~/.dbt

  build-docker:
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: [test-airflow-dags, test-dbt]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Airflow image
        uses: docker/build-push-action@v4
        with:
          context: ./src/infrastructure/docker
          file: ./src/infrastructure/docker/airflow.Dockerfile
          push: false
          tags: data-pipeline/airflow:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max 